#!/usr/bin/env python3
"""Wrap the report fragment into a standalone page for GitHub Pages.

docs/report.html is authored as a fragment (no <!doctype>, <html>, <head> or
<body>), because that is what the Artifact publisher expects -- it supplies the
document skeleton itself. GitHub Pages serves the file verbatim, so it needs a
real document: without a doctype the browser falls into quirks mode, and without
a viewport meta the page renders at 980px and zooms out on a phone.

Run after editing docs/report.html:
    python3 scripts/08_build_pages.py
"""

from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
FRAGMENT = ROOT / "docs" / "report.html"
PAGE = ROOT / "docs" / "index.html"

DESCRIPTION = (
    "Are O4 and O7 independent lines of evidence? An analysis of CancerHotspots "
    "and COSMIC against the SVIG-UK oncogenicity framework, and a proposal for "
    "capping the combined contribution of variant recurrence and hotspot evidence."
)

BANNER = "<!-- Generated by scripts/08_build_pages.py from docs/report.html. Do not edit. -->"


def main() -> None:
    fragment = FRAGMENT.read_text(encoding="utf-8")

    match = re.search(r"<title>(.*?)</title>", fragment, re.S)
    if not match:
        raise SystemExit("docs/report.html has no <title>; cannot build the page.")
    title = match.group(1).strip()

    # The <title> and the font <link>s belong in the head, not the body. The
    # title is re-emitted above, so only the links are carried through.
    hoisted = re.findall(r"^<(?:title|link)\b.*$", fragment, re.M)
    head_tags = [tag for tag in hoisted if not tag.startswith("<title")]
    body = fragment
    for tag in hoisted:
        body = body.replace(tag + "\n", "", 1)

    page = "\n".join(
        [
            "<!doctype html>",
            '<html lang="en">',
            "<head>",
            BANNER,
            '<meta charset="utf-8">',
            '<meta name="viewport" content="width=device-width, initial-scale=1">',
            f"<title>{title}</title>",
            f'<meta name="description" content="{DESCRIPTION}">',
            *head_tags,
            "</head>",
            "<body>",
            body.strip(),
            "</body>",
            "</html>",
            "",
        ]
    )

    PAGE.write_text(page, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(ROOT)} ({len(page):,} bytes) from {FRAGMENT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
